### ISSUE TITLE
Component names should be PascalCase

### ISSUE THREAD

**Issue by julian-hecker** [CharlesStover/optimal-react-file-structure#9]
According to [Reactjs docs](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized), 
> User-Defined Components Must Be Capitalized

So it would make sense to change component directories and references to be capitalized as specified in the docs!

**Comment by CharlesStover** [comment]
Component names being capitalized is not the same as file names being capitalized. Component names being capitalized was a way for React to distinguish between custom components and HTML elements when executing `createElement`; I'm not sure if this is still the case, but it was in legacy React versions. File name capitalization can cause issues on Windows machines, which are case-insensitive.

Uppercase file names goes against established standards for file naming conventions. [[1]](https://www.paho.org/par/index.php?option=com_docman&view=download&category_slug=publicaciones-de-la-representacion&alias=561-guide-to-proper-file-naming-1&Itemid=253) [[2]](https://stackoverflow.com/questions/1594014/how-do-i-explain-my-colleagues-that-filenames-should-not-contain-uppercase-chara) and my favorite [[3]](https://developers.google.com/style/filenames)

It was a deliberate decision to stray from the create-react-app default naming convention to move towards a lowercase implementation.

**Comment by julian-hecker** [comment]
I see! Thanks for feedback!
